/*
    this file is used to create the database structure from scratch.
    run it once, before starting the project.
*/

CREATE DATABASE IF NOT EXISTS orizon;

/*
    "USE orizon" tells MySQL: from this point on,
    all the operations i write concern the "orizon" database.
    without this line, MySQL would not know in which database to create the tables.
*/
USE orizon;

/*
    table: countries

    each country has:
    - id:   integer, automatically generated by the database (AUTO_INCREMENT),
            used as primary key (PRIMARY KEY) to identify each row uniquely.
    - name: string of up to 100 characters, required (NOT NULL).
*/
CREATE TABLE IF NOT EXISTS countries ( /* "IF NOT EXISTS" means: create the table only if it does not already exist */
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

/*
    table: trips

    each trip has:
    - id:     primary key, automatically generated.
    - title:  string of up to 200 characters, required.
    - seats:  integer representing available seats, required.
*/
CREATE TABLE IF NOT EXISTS trips (
    id     INT NOT NULL AUTO_INCREMENT,
    title  VARCHAR(200) NOT NULL,
    seats  INT NOT NULL,
    PRIMARY KEY (id)
);

/*
    table: trip_countries

    a trip can include multiple countries (e.g. France and Spain),
    and the same country can appear in multiple trips.
    this is called a "many-to-many" relationship.

    it cannot be represented directly in SQL:
    the solution is to create an intermediate table that stores
    pairs of ids: (trip_id, country_id).

    PRIMARY KEY (trip_id, country_id):
    the primary key is composed of both columns together.
    this prevents the same pair from being inserted twice.

    FOREIGN KEY:
    a foreign key is a constraint that guarantees data consistency.
    "trip_id must be an id that exists in the trips table" and
    "country_id must be an id that exists in the countries table".
    if i try to insert an id that does not exist, MySQL returns an error.

    ON DELETE CASCADE:
    if i delete a trip, MySQL automatically deletes
    all rows in this table that are linked to it.
    the same applies to countries.
*/
CREATE TABLE IF NOT EXISTS trip_countries (
    trip_id INT NOT NULL,
    country_id INT NOT NULL,
    PRIMARY KEY (trip_id, country_id),
    FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE CASCADE
);
