<?php
/*
    this file contains all the operations on countries.
    each operation corresponds to a method of the CountryController class.

    the routes handled are:
    GET    /countries      → reads all countries
    POST   /countries      → creates a new country
    PUT    /countries/{id} → updates an existing country
    DELETE /countries/{id} → deletes an existing country

    a SQL injection is an attack where someone inserts SQL code
    inside a data field (e.g. the "name" field) to manipulate the database.
    the solution is "prepared statements":
    instead of building the query as a string with values embedded in it,
    i write the query with placeholders like ":id" or ":name",
    and then pass the values separately with "bindValue()".
    this way the database receives the query structure FIRST,
    then receives the values AFTER, as pure data.
    no matter what the value contains: it will never be interpreted as SQL.

    note on the name "$stmt":
    "stmt" is an abbreviation of "statement" (a prepared SQL statement).
    it is a very common PHP convention, not an obligation.
    i could call it $query or $command, but $stmt is the standard.

    note on PDO::PARAM_INT:
    when a value is an integer (like an id), i pass PDO::PARAM_INT
    as the third argument of bindValue().
    this tells PDO: "treat this value as an integer, not as text".
    for text values (like a name) this is not necessary,
    because PDO::PARAM_STR is the default type.

    why use a class instead of standalone functions?
    the controller groups all related operations into one object.
    the PDO connection is stored in the $pdo property once in the constructor,
    so every method can access it via $this->pdo without needing it
    passed as a parameter each time.
*/
class CountryController {

    /*
        property: $pdo
        stores the PDO connection instance passed from index.php.
        declaring it "private" means only methods of this class can access it.
    */
    private PDO $pdo;

    /*
        the constructor runs automatically when i write "new CountryController($pdo)".
        it receives the connection and stores it in the $pdo property.
    */
    public function __construct(PDO $pdo) {
        $this->pdo = $pdo;
    }


    /*
        method: getAll()

        retrieves all countries from the table and returns them as JSON.

        "fetchAll()" retrieves all rows resulting from the query
        and returns them as an array of associative arrays.
        example:
            ['id' => 1, 'name' => 'Italy'],
            ['id' => 2, 'name' => 'France']

        thanks to the FETCH_ASSOC option set in config/database.php,
        every row is automatically an associative array.
    */
    public function getAll(): void {
        $stmt = $this->pdo->prepare('SELECT id, name FROM countries');
        $stmt->execute();

        $countries = $stmt->fetchAll();

        sendJson($countries, 200);
    }


    /*
        method: create()

        creates a new country by reading the "name" field from the JSON request body.
    */
    public function create(): void {
        /*
            i read the data sent by the client (the JSON in the request body).
            after this line, $data is a PHP array, for example:
            ['name' => 'Italy']
        */
        $data = readJsonInput();

        /*
            "empty()" returns true if the variable does not exist or is empty ("", 0, null, []).
            if "name" was not sent or is an empty string, i respond with a 422 error.
            422 means "the submitted data is not valid or is incomplete".
        */
        if (empty($data['name'])) {
            sendJson(['error' => 'The "name" field is required.'], 422);
        }

        $stmt = $this->pdo->prepare('INSERT INTO countries (name) VALUES (:name)');
        $stmt->bindValue(':name', $data['name']);
        $stmt->execute();

        /*
            "lastInsertId()" returns the id automatically generated by the last INSERT.
            i cast it to integer with "(int)" because PDO returns it as a string.
        */
        $id = (int) $this->pdo->lastInsertId();

        sendJson(['message' => 'Country created.', 'id' => $id], 201);
    }


    /*
        method: update($id)

        updates the name of an existing country.
        i receive "$id" as a parameter: it is the id extracted from the URL in index.php.
        example: PUT /countries/3 → $id equals 3.
    */
    public function update(int $id): void {
        $data = readJsonInput();

        if (empty($data['name'])) {
            sendJson(['error' => 'The "name" field is required.'], 422);
        }

        /*
            before updating, i verify that the country with that id actually exists.

            "fetch()" (without "All") retrieves only one row.
            if the query finds no row, fetch() returns "false".
        */
        $check = $this->pdo->prepare('SELECT id FROM countries WHERE id = :id');
        $check->bindValue(':id', $id, PDO::PARAM_INT);
        $check->execute();

        if (!$check->fetch()) { // "if (!$check->fetch())" means "if no row was found"
            sendJson(['error' => 'Country not found.'], 404);
        }

        $stmt = $this->pdo->prepare('UPDATE countries SET name = :name WHERE id = :id');
        $stmt->bindValue(':name', $data['name']);
        $stmt->bindValue(':id', $id, PDO::PARAM_INT);
        $stmt->execute();

        sendJson(['message' => 'Country updated.'], 200);
    }


    /*
        method: delete($id)

        deletes a country by its id.
        thanks to the CASCADE defined in migrations.sql, MySQL automatically
        deletes all rows in "trip_countries" linked to this country.
    */
    public function delete(int $id): void {
        $check = $this->pdo->prepare('SELECT id FROM countries WHERE id = :id');
        $check->bindValue(':id', $id, PDO::PARAM_INT);
        $check->execute();

        if (!$check->fetch()) {
            sendJson(['error' => 'Country not found.'], 404);
        }

        $stmt = $this->pdo->prepare('DELETE FROM countries WHERE id = :id');
        $stmt->bindValue(':id', $id, PDO::PARAM_INT);
        $stmt->execute();

        sendJson(['message' => 'Country deleted.'], 200);
    }
}
